version: '3.6'

services:
  django:
    build: .
    hostname: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./datatube/:/usr/src/app/
      - ./database/:/usr/src/database/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=datatube_django
      - POSTGRES_PASSWORD=:^O
      - POSTGRES_DB=datatube_backend
        
volumes:
  postgres_data:
