# Generated by Django 4.1.2 on 2022-10-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datatubeapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
