# Generated by Django 4.1.2 on 2022-11-02 21:51

from django.db import migrations
from pathlib import Path
import pandas as pd

def import_kaggle_data(apps, schema_editor):
    Video = apps.get_model('datatubeapp', 'Video')
    kaggle_path = Path('../db/kaggle_data/USvideos.csv')
    kaggle_data = pd.read_csv(kaggle_path)
    kaggle_data = kaggle_data[['video_id', 'title', 'description']]
    for _, row in kaggle_data.iterrows():
        video = Video(title=row.title, videoid=row.video_id, description=row.description)
        video.save()

class Migration(migrations.Migration):

    dependencies = [
        ("datatubeapp", "0002_video_description"),
    ]

    operations = [
            migrations.RunPython(import_kaggle_data)
            ]
