# Generated by Django 4.1.2 on 2022-11-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatubeapp', '0002_video_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel', models.TextField(primary_key=True, serialize=False)),
                ('channel_url', models.TextField(null=True)),
                ('subscribers', models.TextField(null=True)),
                ('views', models.TextField(null=True)),
                ('joined', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
