# Generated by Django 4.1.2 on 2022-11-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatubeapp', '0003_channel_remove_video_id_video_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='categoryid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='commentcount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
