# Generated by Django 4.1.2 on 2022-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatubeapp', '0004_video_categoryid_video_commentcount_video_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
