name: Tests
  
on:
  
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

      
  workflow_dispatch:

    
jobs:
  
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Startup containers
      run: docker-compose up -d
    - name: Wait for containers to finish startup
      run: timeout 500 ./deploy_tools/ci_check.sh
    - name: Run unit-tests
      run: docker exec datatube_django_1 python manage.py test datatubeapp
